config/routes.rb
HelpDesk::Application.routes.draw do
  root :to => "tickets#index"

  resources :tickets

end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  attr_accessible :description, :issue
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_filter :find_ticket, :only => [:show, :edit, :update, :destroy]
  def index
    @tickets = Ticket.all
  end

  def new
    @ticket = Ticket.new
  end

  def create
    @ticket = Ticket.new(params[:ticket])
    if @ticket.save
      TicketMailer.new_ticket(@ticket).deliver
      flash[:notice]="Ticket created."
      redirect_to @ticket
    else
      flash[:alert]="Could not create ticket."
      render :action => "new"
    end
  end

  def show
    #
  end

private
  def find_ticket
    @ticket = Ticket.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/layouts/_nav.html.erb
<nav class="top-bar">
  <ul class="title-area">
    <li class="name">
      <h1><%= link_to "Help Desk", root_path %></h1>
    </li>
    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
  </ul>
  <section class="top-bar-section">
    <ul class="left">
      <li class="divider"></li>
      <li><%= link_to "New Ticket", new_ticket_path %></li>
      <li class="divider"></li>
    </ul>
  </section>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  	<title><%= content_for?(:title) ? yield(:title) : "Help Desk" %></title>

  	<%= stylesheet_link_tag    "application" %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <div class="row">
      <div class="panel large-8 large-centered columns">
        <% flash.each do |key,value| %>
        <div class="flash" id="<%= key %>">
          <%= value %>
        </div>
        <% end %>
        <%= render 'layouts/nav' %>
        <%= yield %>
      </div>
    </div>


    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/tickets/_form.html.erb
<%= form_for(@ticket) do |f| %>
  <%= f.error_messages %>

  <%= f.label :issue %>
  <%= f.text_field :issue %>

  <%= f.label :description %>
  <%= f.text_field :description %>

  <%= f.submit %>
<% end %>

app/views/tickets/index.html.erb
<h2>Help Desk Tickets</h2>
<ul>
  <% @tickets.each do |ticket| %>
   <li><%= link_to ticket.issue, ticket_path(ticket) %></li>
  <% end %>
</ul>
<%= link_to "New Ticket", new_ticket_path, :class => "button" %>

app/views/tickets/new.html.erb
<h2>New Ticket</h2>
<%= render "form" %>

app/views/tickets/show.html.erb
<h2>Ticket</h2>
<h4><%= @ticket.issue %></h4>
<p><%= @ticket.description %></p></br>
<p>Created <%= timeago_tag @ticket.created_at %></p>